[package]
name = "nova_poc"
version = "0.1.0"
edition = "2021"

[dependencies]
bellpepper-core = "0.4.0"
bincode = "1.3.3"
ff = "0.13.0"
flate2 = "1.0.30"
generic-array = "1.1.0"
neptune = "13.0.0"
nova-snark = {version = "0.37.0", features = [  ], default-features = false}
rand = "0.8.5"
